# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 15-400 Project // Sonya Anopa
email: sanopa@cmu.edu
description: > # this means to ignore newlines until "baseurl:"
 This site is a web page for the 15-400 project to be completed
 during in the Spring 2016 semester at Carnegie Mellon. The project
 proposal, as well as any updates along the way, will be posted here.
baseurl: "" # the subpath of your site, e.g. /blog
github_username: sanopa

# Build settings
markdown: kramdown
safe: true
lsi: false
highlighter: pygments
